name: build

on:
  workflow_dispatch:

  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    uses: ./.github/workflows/builder.yml
    secrets: inherit
    permissions:
      packages: write

    strategy:
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]

    with:
      runner: ${{ matrix.runner }}

  merge:
    runs-on: ubuntu-latest
    name: merge manifests
    needs: build
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v6

      - uses: oras-project/setup-oras@v1

      - run: echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin

      - run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          for src in ./src/scripts/*.sh; do
            variant=$(basename "$src" ".sh")
            echo "Merging variant: $variant"
            oras manifest index create ghcr.io/$REPO:$variant $variant_amd64 $variant_arm64
          done
